name: vexa_retailer
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_GATEWAY_HOST_PORT:-28056}:8000"
    environment:
      - LOG_LEVEL=DEBUG
      - VEXA_INFRA_API_URL=${VEXA_INFRA_API_URL}
      - VEXA_INFRA_API_KEY=${VEXA_INFRA_API_KEY}
      - REDIS_URL=redis://redis:6379/0
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=vexa
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - ADMIN_API_TOKEN=${ADMIN_API_TOKEN}
    init: true
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - vexa_default
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=vexa
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d vexa"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - vexa_default
    restart: unless-stopped
    ports:
      - "${POSTGRES_HOST_PORT:-25438}:5432"

volumes:
  postgres-data:

networks:
  vexa_default:
    driver: bridge
